kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  namespace: default
  annotations:
    avp.kubernetes.io/path: "avp/data/second-secret"
type: Opaque
stringData:
  sample-secret: <value>
